<a href="https://colab.research.google.com/github/michaelwnau/_ai_academy_notebooks/blob/main/Week8_tues_nau_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Workshop 8 [Student]

This notebook will cover the following topics:

1. Numpy Array
2. Reading data from CSV
3. Statistics
4. Indexing
5. Copy vs View
6. Modifications

## 8.1 NUMPY ARRAY (Follow)

**Learning Objectives:**

1. Understand the numpy module.
2. Understand numpy arrays.
3. Understand Array creation and basic functions.
4. Learn to manipulate arrays

In [ ]:
#https://numpy.org/doc/stable/reference/arrays.dtypes.html
"""
Add comments for you own reference
"""

import numpy as np
x = np.array([
              [1,2,3,4,5],
              [6,7,8,9,0],
              [5,4,3,2,1]
            ])
print(x)
print("Type -",type(x))
print("Data Type -",x.dtype)
print("Size -",x.size)
print("ItemSize -",x.itemsize)
print("Dimensions -",x.ndim)
print("Shape -",x.shape)

[[1 2 3 4 5]
 [6 7 8 9 0]
 [5 4 3 2 1]]
Type - <class 'numpy.ndarray'>
Data Type - int64
Size - 15
ItemSize - 8
Dimensions - 2
Shape - (3, 5)


In [ ]:
"""
Add comments for you own reference
"""

import numpy as np
x = np.full(5,3)
print("Full:\n",x)
x = np.zeros((2,4))
print("Zeros:\n",x)
x = np.ones((2,5))
print("Ones:\n",x)
x = np.arange(1,7)
print("Range:\n",x)
x = np.linspace(1,5,6)
print("LinSpace:\n",x)

Full:
 [3 3 3 3 3]
Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Range:
 [1 2 3 4 5 6]
LinSpace:
 [1.  1.8 2.6 3.4 4.2 5. ]


In [ ]:
"""
Add comments for you own reference
"""

import numpy as np
x = np.arange(1,10)
print("Array X:\n",x,"\n")
print("Multiplication:\n",x*2,"\n")
print("Substraction:\n",x-2,"\n")
y = np.arange(3,12)
print("Array Y:\n",y,"\n")
print("SHAPES -",x.shape,y.shape,"\n")
print("Addition:\n",x+y,"\n")
print("Multiplication:\n",x*y,"\n")

Array X:
 [1 2 3 4 5 6 7 8 9] 

Multiplication:
 [ 2  4  6  8 10 12 14 16 18] 

Substraction:
 [-1  0  1  2  3  4  5  6  7] 

Array Y:
 [ 3  4  5  6  7  8  9 10 11] 

SHAPES - (9,) (9,) 

Addition:
 [ 4  6  8 10 12 14 16 18 20] 

Multiplication:
 [ 3  8 15 24 35 48 63 80 99] 



**Evaluation:**

After running this program, think about and answer these questions:

1. What does the arange function do?
2. What is the use of 1s and 0s function?
3. What will happen if shapes of arrays are not same?
4. Try to add more dimentions to the arrays.

## 8.1 NUMPY ARRAY (Group)

Write a program that will do the following:

1. Create 3 Arrays:
    - X : containing Multiples of 5
    - Y : in range of 100 to 150
    - Z : containing all n (taken from user) 
2. Make sure that Shapes of arrays are equal.
3. Perform:
    - X + Y
    - X * Z
    - Z - Y
    - X + Y + Z

In [ ]:
# import numpy as np

# x = np.arange(1,151,5)
# y = np.arange(100,151)
# z = np.arange(list(map(int, input("Enter range integers for Z: ").split(","))))


# print(x)
# print(y)
# print(z)

# # check shapes are equal
# if x.shape == y.shape == z.shape:
#     print("Shapes of arrays are equal.")
# else:
#     print("Shapes of arrays are not equal.")

# # perform operations
# print("X + Y = ", x + y)
# print("X * Z = ", x*y)
# print("Z - Y = ", z - y)
# print("X + Y + Z = ", x + y + z)

Enter range integers for Z: 1, 250


TypeError: ignored

In [ ]:
# import numpy as np

# x = np.arange(1, 151, 5)
# y = np.arange(100, 151)
# z = np.array(list(map(int, input("Enter two comma-separated integers for Z: ").split(","))))

# # check length of z and add 1s to make it the same length as x
# if len(z) != len(x):
#     num_to_add = len(x) - len(z)
#     z = np.concatenate((z, np.ones(num_to_add, dtype=int)))

# print(x)
# print(y)
# print(z)

# # check shapes are equal
# if x.shape == y.shape == z.shape:
#     print("Shapes of arrays are equal.")
# else:
#     print("Shapes of arrays are not equal.")

# # perform operations
# print("X + Y = ", x + y)
# print("X * Z = ", x * z)
# print("Z - Y = ", z - y)
# print("X + Y + Z = ", x + y + z)
# #

Enter two comma-separated integers for Z: 1, 50
[  1   6  11  16  21  26  31  36  41  46  51  56  61  66  71  76  81  86
  91  96 101 106 111 116 121 126 131 136 141 146]
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150]
[ 1 50  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1]
Shapes of arrays are not equal.


ValueError: ignored

In [ ]:
# Procrustean version
"""
In this version, arrays Y and Z are truncated to equal the length of X.
"""

import numpy as np

x = np.arange(1, 151, 5)
y = np.arange(100, 151)
z = np.array(list(map(int, input("Enter two comma-separated integers for Z: ").split(","))))

# check length of z and add 1s to make it the same length as x
if len(z) != len(x):
    num_to_add = len(x) - len(z)
    z = np.concatenate((z, np.ones(num_to_add, dtype=int)))

# truncate y and z if they are not the same length as x or z
if len(y) != len(x) or len(z) != len(x):
    min_length = min(len(x), len(z))
    x = x[:min_length]
    y = y[:min_length]
    z = z[:min_length]

print(f'This is array X: {x}')
print(f'This is array Y: {y}')
print(f'This is array Z: {z}')

# check shapes are equal
if x.shape == y.shape == z.shape:
    print("Shapes of arrays are equal.")
else:
    print("Shapes of arrays are not equal.")

# perform operations
print("X + Y = ", x + y)
print("X * Z = ", x * z)
print("Z - Y = ", z - y)
print("X + Y + Z = ", x + y + z)


Enter two comma-separated integers for Z: 1, 3
This is array X: [  1   6  11  16  21  26  31  36  41  46  51  56  61  66  71  76  81  86
  91  96 101 106 111 116 121 126 131 136 141 146]
This is array Y: [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129]
This is array Z: [1 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Shapes of arrays are equal.
X + Y =  [101 107 113 119 125 131 137 143 149 155 161 167 173 179 185 191 197 203
 209 215 221 227 233 239 245 251 257 263 269 275]
X * Z =  [  1  18  11  16  21  26  31  36  41  46  51  56  61  66  71  76  81  86
  91  96 101 106 111 116 121 126 131 136 141 146]
Z - Y =  [ -99  -98 -101 -102 -103 -104 -105 -106 -107 -108 -109 -110 -111 -112
 -113 -114 -115 -116 -117 -118 -119 -120 -121 -122 -123 -124 -125 -126
 -127 -128]
X + Y + Z =  [102 110 114 120 126 132 138 144 150 156 162 168 174 180 186 192 198 204
 210 216 222 228 234 240 246 252 258 264 270 276]


## 8.2 READING CSV (Follow)

**Learning Objectives:**

1. Understand how to read CSV into arrays.
2. Understand the data type of csv files.
3. Learn to manipulate CSV data.

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np

data = np.loadtxt("test.csv",delimiter=",", dtype=int)
print(data)

[[53 28 85 13 57 72 46 31 73 32]
 [50 90 87 98 82 35 86 30  2 43]
 [74 53 77  1 69 97 76 21 75  3]
 [61 67  7 21  6 55 63 42 77  6]
 [58 82 77  7 68 93 41 75 77 19]
 [59 55 52 63 12 74 11  7 84 40]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]
 [40  9 25 88 61 86 93 77 74 73]
 [81 58 13 30 41 41 50 44 90  1]
 [87 37 73 14 10 11 21 84 68 22]
 [33  6 82 37 92 32 83  1 58 79]
 [61 53 64 77 19 56 44 31 78 93]
 [51 34 46 54 13 72 48 65 19 83]
 [33 41 58 45 41 66 22 17 40 59]
 [37 38 10  3 89 14 12 22  1  3]
 [96 69 80 85  6 12 34 69 80 59]
 [67 90 93 69 73 89 47 98 73 57]
 [66 97  7 18 39 84  4 26 21 81]
 [20 66 56 59 66 53  2 64 73 12]
 [89  8 26 29 49 82 39 22 31 33]
 [49 76 11 30 28 21 18 57 95 69]
 [92 81 85 26 21  7 58 48 47 56]
 [37 80 41 91 59 28 85  6 68 74]
 [26 90 31 28 23 45 18 23 67 53]
 [83 17 30 50 92 23 76  7 33 67]
 [69 20 46 89 42 30 67 36 26 49]
 [83 61 82  6 30 22 34 75 64 78]
 [86 18 80

In [ ]:
"""
Add comments for you own reference
"""

print("Type -",type(data))
print("Data Type -",data.dtype)
print("Size -",data.size)
print("ItemSize -",data.itemsize)
print("Dimensions -",data.ndim)
print("Shape -",data.shape)

Type - <class 'numpy.ndarray'>
Data Type - int64
Size - 1000
ItemSize - 8
Dimensions - 2
Shape - (100, 10)


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


**Evaluation:**

After running this program, think about and answer these questions:

1. What does astype() function do?
2. Search for alternate methods of loading.
3. What is the use of delimiter parameter?

## 8.2 READING CSV (Group)

Write a program that will do the following:

1. Read csv file 'test.csv'
2. Perform basic operations on 'test.csv'
    - Multiply each value by 2
    - Subtract each value by 50
3. Create an array X with same shape and random numbers
4. Add X to data
   

In [ ]:
import numpy as np

data = np.loadtxt("test.csv", delimiter=",", dtype=int)




In [ ]:
import numpy as np
import pandas as pd

# read csv file
df = pd.read_csv('test.csv')

# perform basic operations on data
df = df * 2 - 50

# create array X with same shape and random numbers
X = np.random.rand(*df.shape)

# add X to data
df = df + X

# print final data
print(df)


            53          28          85          13          57          72  \
0    50.317563  130.259289  124.418719  146.800680  114.834183   20.443990   
1    98.190131   56.001218  104.064518  -47.949623   88.112782  144.630702   
2    72.381567   84.455727  -35.484346   -7.871819  -37.214315   60.865576   
3    66.321886  114.990098  104.539408  -35.757399   86.759261  136.102552   
4    68.133375   60.766398   54.903671   76.603277  -25.947973   98.171020   
..         ...         ...         ...         ...         ...         ...   
94  -37.027135   74.938041  -27.534586   84.014876  -31.219041  -17.166393   
95   42.219290  -41.728134   -5.683995   -9.895224   38.299418   72.204506   
96  120.764126   80.287125   80.761089   92.630110   18.192607   -7.000112   
97  130.708644   38.750781    0.210035   -5.934159  -37.508414  -17.952328   
98   66.973729   90.157198  100.230621   34.212112    0.233473   66.053854   

            46          31          73          32  
0   122.07

## 8.3 STATISTICS (Follow)

**Learning Objectives:**

1. Learn to perform statistical functions on Arrays.
2. Understand how arrays provide statistical analysis.
3. Understand how to perform statistical analysis of different dimensions of an array.

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np

data = np.loadtxt("test.csv",delimiter=",", dtype=int)

print("Mean -")
print(data.mean())
print("Median -")
print(np.median(data))
print("Sum -")
print(np.sum(data[0]))
print("Standard Deviation -")
print(np.std(data))
print("Variance -")
print(np.var(data))

Mean -
49.305
Median -
51.0
Sum -
490
Standard Deviation -
28.376398203436604
Variance -
805.2199750000001


In [ ]:
#https://railsware.com/blog/python-for-machine-learning-pandas-axis-explained/#:~:text=%E2%80%9Caxis%200%E2%80%9D%20represents%20rows%20and,it%20goes%20along%20rows%20direction.
"""
Add comments for you own reference
"""

print("Mean by Rows-")
print(data.mean(axis=0))
print("Mean by Column-")
print(data.mean(axis=1))

Mean by Rows-
[51.82 49.84 50.13 51.28 47.67 45.82 48.37 49.49 49.85 48.78]
Mean by Column-
[49.  60.3 54.6 40.5 59.7 45.7 44.8 45.8 46.6 67.4 62.6 44.9 42.7 50.3
 57.6 48.5 42.2 22.9 59.  75.6 44.3 47.1 40.8 45.4 52.1 56.9 40.4 47.8
 47.4 53.5 47.6 49.2 50.4 52.1 53.4 45.6 57.5 60.5 51.8 30.5 37.3 65.5
 49.1 53.  44.8 40.6 60.  62.1 44.6 33.9 54.4 41.3 50.3 38.8 60.3 41.5
 41.5 44.3 34.4 47.8 31.3 31.7 61.5 53.8 51.6 54.3 44.3 71.  41.2 52.5
 42.4 61.5 47.8 55.3 53.1 39.5 48.6 56.1 38.5 52.  55.5 50.9 50.3 39.6
 47.7 49.2 58.8 43.8 49.2 53.5 58.4 54.1 38.  66.3 58.6 37.7 51.1 50.4
 39.1 49.8]


**Evaluation:**

After running this program, think about and answer these questions:

1. What other functions are readily available?
2. What does axis parameter do?
3. How will different functions react to changes in dimensions of the array?

## 8.3 STATISTICS (Group)

Write a program that will do the following:

1. Get a number n from User (10-30)
2. Print the statistic information for every nth row of the 'test.csv'
    - Mean
    - Median
    - Sum
    - SD
    - Variance


In [ ]:
import numpy as np
import pandas as pd

# read csv file
df = pd.read_csv('test.csv')

# get input from user for n
n = int(input("Enter a number between 10 and 30: "))

# check if n is within range
if n < 10 or n > 30:
    print("Error: n is not within range.")
else:
    # print statistics for every nth row
    for i in range(n-1, len(df), n):
        row = df.iloc[i]
        print(f"Statistics for Row {i+1}:")
        print(f"Mean: {np.mean(row)}")
        print(f"Median: {np.median(row)}")
        print(f"Sum: {np.sum(row)}")
        print(f"Standard Deviation: {np.std(row)}")
        print(f"Variance: {np.var(row)}")
        print()



Enter a number between 10 and 30: 20
Statistics for Row 20:
Mean: 44.3
Median: 32.5
Sum: 443
Standard Deviation: 32.83915346046545
Variance: 1078.4099999999999

Statistics for Row 40:
Mean: 37.3
Median: 27.5
Sum: 373
Standard Deviation: 34.339627254820336
Variance: 1179.2099999999998

Statistics for Row 60:
Mean: 31.3
Median: 20.5
Sum: 313
Standard Deviation: 25.47174905655283
Variance: 648.81

Statistics for Row 80:
Mean: 55.5
Median: 66.0
Sum: 555
Standard Deviation: 28.800173610587837
Variance: 829.45



## 8.4 INDEXING (Follow)

**Learning Objectives:**

1. Understand how Indexing in arrays works.
2. Understand how slicing in arrays works.
3. Learn to extract relevant information from numpy array.

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np

data = np.loadtxt("test.csv",delimiter=",", dtype=int)

print('Item at index (20,4):\n',data[20,4],'\n')

Item at index (20,4):
 39 



In [ ]:
"""
Add comments for you own reference
"""

print('Slice of rows 20 - 24:\n',data[20:25],'\n')

print('Specific rows (multiples of 10):\n',data[[i for i in range(0,100,10)]],'\n')

print('Specific rows (multiples of 10):\n',data[0:100:10],'\n')

Slice of rows 20 - 24:
 [[66 97  7 18 39 84  4 26 21 81]
 [20 66 56 59 66 53  2 64 73 12]
 [89  8 26 29 49 82 39 22 31 33]
 [49 76 11 30 28 21 18 57 95 69]
 [92 81 85 26 21  7 58 48 47 56]] 

Specific rows (multiples of 10):
 [[53 28 85 13 57 72 46 31 73 32]
 [40  9 25 88 61 86 93 77 74 73]
 [66 97  7 18 39 84  4 26 21 81]
 [86 18 80 32 77 54  2 17 75 35]
 [42  8 78 74 99  5  3  3 48 13]
 [45 99 25 94 38 80 22 15 59 67]
 [17  8 24 88 35 17 45 62  2 15]
 [26 69  9 85 20 51 66  7 81 10]
 [97 90 69 73 28 13 68 41 12 64]
 [59 70 25 94 67  2 87 65 53 62]] 

Specific rows (multiples of 10):
 [[53 28 85 13 57 72 46 31 73 32]
 [40  9 25 88 61 86 93 77 74 73]
 [66 97  7 18 39 84  4 26 21 81]
 [86 18 80 32 77 54  2 17 75 35]
 [42  8 78 74 99  5  3  3 48 13]
 [45 99 25 94 38 80 22 15 59 67]
 [17  8 24 88 35 17 45 62  2 15]
 [26 69  9 85 20 51 66  7 81 10]
 [97 90 69 73 28 13 68 41 12 64]
 [59 70 25 94 67  2 87 65 53 62]] 



In [ ]:
"""
Add comments for you own reference
"""

print('Slice of columns 5 - 7:\n',data[:,5:8],'\n')
print('Specific columns (multiples of 2):\n',data[:,[i for i in range(0,10,2)]],'\n')

Slice of columns 5 - 7:
 [[72 46 31]
 [35 86 30]
 [97 76 21]
 [55 63 42]
 [93 41 75]
 [74 11  7]
 [46 73 79]
 [83 30 32]
 [18 16 44]
 [52 81 64]
 [86 93 77]
 [41 50 44]
 [11 21 84]
 [32 83  1]
 [56 44 31]
 [72 48 65]
 [66 22 17]
 [14 12 22]
 [12 34 69]
 [89 47 98]
 [84  4 26]
 [53  2 64]
 [82 39 22]
 [21 18 57]
 [ 7 58 48]
 [28 85  6]
 [45 18 23]
 [23 76  7]
 [30 67 36]
 [22 34 75]
 [54  2 17]
 [99 66 53]
 [83  6 23]
 [65 92 56]
 [32 16 95]
 [29 10 60]
 [99 32 71]
 [51 91 86]
 [44 51 36]
 [66 17 29]
 [ 5  3  3]
 [72 62 73]
 [10 77 91]
 [ 8 75 44]
 [ 4  1 78]
 [32 60 63]
 [ 8  2 32]
 [66 22 97]
 [51 36 78]
 [ 2 40 10]
 [80 22 15]
 [69 24 76]
 [61 16 68]
 [55 23 68]
 [66 46 24]
 [74  7 86]
 [23 69 51]
 [34 96 42]
 [ 3 62 26]
 [10 65 95]
 [17 45 62]
 [ 5  4 47]
 [98 83 53]
 [22  5 41]
 [70 88  6]
 [65 81 97]
 [10 13  5]
 [79 93 66]
 [25 82 24]
 [67 87 66]
 [51 66  7]
 [63 38 69]
 [60 18  3]
 [12 98 86]
 [54 64 71]
 [45 46 57]
 [ 6 68 95]
 [11 26 64]
 [14 25 20]
 [11 84 88]
 [13 68 41]
 [9

In [ ]:
"""
Add comments for you own reference
"""

print('Slice of rows 20-24 & columns 5 - 7:\n',data[20:25,5:8],'\n')

Slice of rows 20-24 & columns 5 - 7:
 [[84  4 26]
 [53  2 64]
 [82 39 22]
 [21 18 57]
 [ 7 58 48]] 



**Evaluation:**

After running this program, think about and answer these questions:

1. What is the use case for slicing and indexing?
2. Try to manipulate the array by slicing differently.

## 8.4 INDEXING (Group)

Write a program that will do the following:

1. Use 'test.csv' 
2. Get a row and column number from the user and display the value at the index
3. Get a range of rows and columns from the user and display all rows in column range and all columns in row range and also all data in row and column range
4. Add rows 10-15 with rows 50-55 and display output

In [ ]:
import numpy as np
import pandas as pd

# read csv file
df = pd.read_csv('test.csv')

# get input from user for row and column numbers or ranges
row_input = input("Enter a row number or range (e.g. 1, 2-5): ")
col_input = input("Enter a column number or range (e.g. 1, 2-5): ")

# function to get rows or columns within a range
def get_range(input_str):
    if '-' in input_str:
        start, end = input_str.split('-')
        return slice(int(start)-1, int(end))
    else:
        return int(input_str)-1

# display value at index
row_idx = get_range(row_input)
col_idx = get_range(col_input)
print(f"Value at ({row_input}, {col_input}): {df.iloc[row_idx, col_idx]}")

# display rows and columns within range
row_range = get_range(row_input)
col_range = get_range(col_input)
if isinstance(row_range, int):
    print(f"All values in Row {row_range+1} and Columns {col_input}:")
    print(df.iloc[row_range, col_range])
else:
    print(f"All values in Rows {row_input} and Columns {col_input}:")
    print(df.iloc[row_range, col_range])
    print()

    print(f"All values in Rows {row_input} and Columns {col_range}:")
    print(df.iloc[row_range, :, col_range])
    print()

# add rows 10-15 with rows 50-55 and display output
df_add = df.iloc[10:16, :] + df.iloc[50:56, :]
print("Result of adding Rows 10-15 with Rows 50-55:")
print(df_add)



KeyboardInterrupt: ignored

## 8.5 COPY VS VIEW (Follow)

**Learning Objectives:**

1. Understand the difference between a copy and a view.
2. Understand how the original array is affected when deling with views.
3. Understand how the original array is affected when deling with copies.
4. Learn to manipulate data using copies and views

In [ ]:
"""
Add comments for you own reference
"""

arr = np.array([1,2,3,4,5])
print("Original Before -")
print(arr)
x = arr.view()
x[0] = 9
print("Original for view -")
print(arr)
print("View -")
print(x)
y = arr.copy()
y[1] = 8
print("Original for copy -")
print(arr)
print("Copy -")
print(y)

Original Before -
[1 2 3 4 5]
Original for view -
[9 2 3 4 5]
View -
[9 2 3 4 5]
Original for copy -
[9 2 3 4 5]
Copy -
[9 8 3 4 5]


In [ ]:
"""
Add comments for you own reference
"""

data = np.loadtxt("test.csv",delimiter=",", dtype=int)
data = data[5:10]

print("Original Before -")
print(data)
x = data.view()
x[0] = 9
print("Original for view -")
print(data)
print("View -")
print(x)
y = data.copy()
y[1] = 8
print("Original for copy -")
print(data)
print("Copy -")
print(y)

Original Before -
[[59 55 52 63 12 74 11  7 84 40]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]
Original for view -
[[ 9  9  9  9  9  9  9  9  9  9]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]
View -
[[ 9  9  9  9  9  9  9  9  9  9]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]
Original for copy -
[[ 9  9  9  9  9  9  9  9  9  9]
 [12 11 46 30 85 46 73 79 31 35]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]
Copy -
[[ 9  9  9  9  9  9  9  9  9  9]
 [ 8  8  8  8  8  8  8  8  8  8]
 [77 20 56 32 21 83 30 32 83 24]
 [24 80 21 79 72 18 16 44 51 61]
 [63 64 95 29 69 52 81 64 92 65]]


**Evaluation:**

After running this program, think about and answer these questions:

1. What does the copy() function do?
2. What does the view() function do?
3. How is the original array affected by manipulating views / copies?
4. What is the best use case for views?
5. What is the best use case for copies?

## 8.5 COPY VS VIEW (Group)

Write a program that will do the following:

1. Read 'test.csv' 
2. Make a copy and a view of the data
3. Convert even rows of view to all 5
4. Convert odd rows of copy to all 10
5. Add Copy to view
6. Display all three Arrays

In [ ]:
import numpy as np
import pandas as pd

# read csv file
df = pd.read_csv('test.csv')

# make a copy and a view of the data
df_copy = df.copy()
df_view = df.copy()

# convert even rows of view to all 5
df_view.iloc[1::2] = 5

# convert odd rows of copy to all 10
df_copy.iloc[::2] = 10

# add copy to view
df_add = df_view + df_copy

# display all three arrays
print("Copy:")
print(df_copy)
print()

print("View:")
print(df_view)
print()

print("Copy + View:")
print(df_add)



Copy:
    53  28  85  13  57  72  46  31  73  32
0   10  10  10  10  10  10  10  10  10  10
1   74  53  77   1  69  97  76  21  75   3
2   10  10  10  10  10  10  10  10  10  10
3   58  82  77   7  68  93  41  75  77  19
4   10  10  10  10  10  10  10  10  10  10
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
94  10  10  10  10  10  10  10  10  10  10
95  46   4  22  20  44  61  59  86  93  76
96  10  10  10  10  10  10  10  10  10  10
97  90  44  25  22   6  16  50  31  88  19
98  10  10  10  10  10  10  10  10  10  10

[99 rows x 10 columns]

View:
    53  28  85  13  57  72  46  31  73  32
0   50  90  87  98  82  35  86  30   2  43
1    5   5   5   5   5   5   5   5   5   5
2   61  67   7  21   6  55  63  42  77   6
3    5   5   5   5   5   5   5   5   5   5
4   59  55  52  63  12  74  11   7  84  40
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
94   6  62  11  67   9  16  34  79  47  46
95   5   5   5   5   5   5   5   5   5   5
96  85  65  65  71  34  21  72  57  20  14
97   5   5   5   

## 8.6 MODIFICATION (Follow)

**Learning Objectives:**

1. Understand how to modify an array.
2. Learn modification functions.
3. Understand the use of array modification

In [ ]:
"""
Add comments for you own reference
"""

import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr, "\n")
arr.resize(2,3) #view
print(arr,"\n")
x = arr.reshape(3,2) #copy
print(x,"\n")

y = x.flatten()  #copy
z = x.ravel()    #view
y[0] = 99
z[0] = 88
print(x,"\n")
print(y,"\n")
print(z,"\n")
print(x.transpose(),"\n")
print(x)

[1 2 3 4 5 6] 

[[1 2 3]
 [4 5 6]] 

[[1 2]
 [3 4]
 [5 6]] 

[[88  2]
 [ 3  4]
 [ 5  6]] 

[99  2  3  4  5  6] 

[88  2  3  4  5  6] 

[[88  3  5]
 [ 2  4  6]] 

[[88  2]
 [ 3  4]
 [ 5  6]]


In [ ]:
"""
Add comments for you own reference
"""

data = np.loadtxt("test.csv",delimiter=",", dtype=str).astype(int)
data = data[25:30]

data.resize(25,2)
print(data,"\n")
x = data.reshape(10,5)
print(x,"\n")
y = x.flatten()
z = x.ravel()
y[0] = 99
z[0] = 88
print(x,"\n")
print(y,"\n")
print(z,"\n")
print(x.transpose(),"\n")

[[37 80]
 [41 91]
 [59 28]
 [85  6]
 [68 74]
 [26 90]
 [31 28]
 [23 45]
 [18 23]
 [67 53]
 [83 17]
 [30 50]
 [92 23]
 [76  7]
 [33 67]
 [69 20]
 [46 89]
 [42 30]
 [67 36]
 [26 49]
 [83 61]
 [82  6]
 [30 22]
 [34 75]
 [64 78]] 

[[37 80 41 91 59]
 [28 85  6 68 74]
 [26 90 31 28 23]
 [45 18 23 67 53]
 [83 17 30 50 92]
 [23 76  7 33 67]
 [69 20 46 89 42]
 [30 67 36 26 49]
 [83 61 82  6 30]
 [22 34 75 64 78]] 

[[88 80 41 91 59]
 [28 85  6 68 74]
 [26 90 31 28 23]
 [45 18 23 67 53]
 [83 17 30 50 92]
 [23 76  7 33 67]
 [69 20 46 89 42]
 [30 67 36 26 49]
 [83 61 82  6 30]
 [22 34 75 64 78]] 

[99 80 41 91 59 28 85  6 68 74 26 90 31 28 23 45 18 23 67 53 83 17 30 50
 92 23 76  7 33 67 69 20 46 89 42 30 67 36 26 49 83 61 82  6 30 22 34 75
 64 78] 

[88 80 41 91 59 28 85  6 68 74 26 90 31 28 23 45 18 23 67 53 83 17 30 50
 92 23 76  7 33 67 69 20 46 89 42 30 67 36 26 49 83 61 82  6 30 22 34 75
 64 78] 

[[88 28 26 45 83 23 69 30 83 22]
 [80 85 90 18 17 76 20 67 61 34]
 [41  6 31 23 30  7 46 36 82

**Evaluation:**

After running this program, think about and answer these questions:

1. What is the difference between resize and reshape?
2. What is the difference between ravel and flatten?
3. What does transpose() function do?
4. How are these functions helpful in data analysis or statistics?

## 8.6 MODIFICATION (Group)

Write a program that will do the following:

1. Read 'test.csv' 
2. Slice a 5:8 grid from the array (X)
3. Make a copy and transpose (X)
4. Reshape both arrays to (4,10)
5. Multiply the arrays and display the Output
6. Try to display each step

In [ ]:
import numpy as np
import pandas as pd

# read csv file
df = pd.read_csv('test.csv')

# select a 4x10 grid from the original DataFrame
X = df.iloc[3:7, :10]

# make a copy and transpose
X_copy = X.copy()
X_T = X.transpose()

# reshape both arrays to (4,10)
X_reshape = X.values.reshape(4, 10)
X_copy_reshape = X_copy.values.reshape(4, 10)

# multiply the arrays and display the output
X_mult = np.multiply(X_reshape, X_copy_reshape)
print("Output:")
print(X_mult)


Output:
[[3364 6724 5929   49 4624 8649 1681 5625 5929  361]
 [3481 3025 2704 3969  144 5476  121   49 7056 1600]
 [ 144  121 2116  900 7225 2116 5329 6241  961 1225]
 [5929  400 3136 1024  441 6889  900 1024 6889  576]]
